### Without any feature engineering

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from pathlib import Path

In [2]:
import os 
from pathlib import Path 
path=Path.cwd().parent

In [3]:
(path/'data/train_flood.csv').exists()

True

In [4]:
df=pd.read_csv(path/'data/train_flood.csv')
df1=pd.read_csv(path/'data/test_flood.csv')

In [5]:
df.head()

,row_id,month,day_of_year,streamflow_today_cumecs,streamflow_anomaly_zscore,flow_rate_of_change,flow_velocity_km_per_day,antecedent_rain_3d_sum,antecedent_rain_7d_sum,antecedent_rain_15d_sum,...,slope_scaled,slope_uav_scaled,forest_cover_scaled,urban_cover_scaled,rain_soilmoisture_interaction,rain_urban_interaction,rain_slope_interaction,rain_basinsize_interaction,uparea_rain_interaction,streamflow_tomorrow_cumecs
0,0,2,3,51.84180,-0.554512,-0.406627,-1.649524,0.0,0.0,0.0,...,-0.564147,0.638676,-0.347207,-1.043051,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,51.435061
1,1,2,3,570.75726,-0.594236,-5.728960,0.206959,0.0,0.0,0.0,...,-0.184717,0.039940,-0.347207,0.183875,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,565.028190
2,2,2,3,45.45640,-1.113376,-0.192057,-1.649524,0.0,0.0,0.0,...,-0.564147,-1.066421,-0.347207,-1.043051,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,45.264231
3,3,2,3,405.39710,-0.729036,-2.480840,0.769118,0.0,0.0,0.0,...,0.068236,2.278693,4.526986,-1.533821,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,402.916149
4,4,2,3,2289.59030,-1.284924,-16.203800,-0.256761,0.0,0.0,0.0,...,-0.311194,-0.728005,-0.347207,0.183875,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,2273.386393

In [6]:
df.shape

(2571055, 34)

In [9]:
Id=df1['row_id']

In [10]:
df.drop('row_id',axis=1,inplace=True)
df1.drop('row_id',axis=1,inplace=True)

In [11]:
df.head()

,month,day_of_year,streamflow_today_cumecs,streamflow_anomaly_zscore,flow_rate_of_change,flow_velocity_km_per_day,antecedent_rain_3d_sum,antecedent_rain_7d_sum,antecedent_rain_15d_sum,antecedent_rain_30d_sum,...,slope_scaled,slope_uav_scaled,forest_cover_scaled,urban_cover_scaled,rain_soilmoisture_interaction,rain_urban_interaction,rain_slope_interaction,rain_basinsize_interaction,uparea_rain_interaction,streamflow_tomorrow_cumecs
0,2,3,51.84180,-0.554512,-0.406627,-1.649524,0.0,0.0,0.0,0.0,...,-0.564147,0.638676,-0.347207,-1.043051,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,51.435061
1,2,3,570.75726,-0.594236,-5.728960,0.206959,0.0,0.0,0.0,0.0,...,-0.184717,0.039940,-0.347207,0.183875,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,565.028190
2,2,3,45.45640,-1.113376,-0.192057,-1.649524,0.0,0.0,0.0,0.0,...,-0.564147,-1.066421,-0.347207,-1.043051,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,45.264231
3,2,3,405.39710,-0.729036,-2.480840,0.769118,0.0,0.0,0.0,0.0,...,0.068236,2.278693,4.526986,-1.533821,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,402.916149
4,2,3,2289.59030,-1.284924,-16.203800,-0.256761,0.0,0.0,0.0,0.0,...,-0.311194,-0.728005,-0.347207,0.183875,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,2273.386393

In [12]:
df['month_cos'] = np.cos(2*np.pi*df['month']/12 )
df['month_sin'] = np.sin(2*np.pi*df['month']/12 )

df1['month_cos'] = np.cos(2*np.pi*df1['month']/12 )
df1['month_sin'] = np.sin(2*np.pi*df1['month']/12 )

In [13]:
df.drop('month',axis=1,inplace=True)
df1.drop('month',axis=1,inplace=True)

In [14]:
df['dayofyear_cos'] = np.cos(2*np.pi*df['day_of_year']/365 )
df['dayofyear_sin'] = np.sin(2*np.pi*df['day_of_year']/365)

df1['dayofyear_cos'] = np.cos(2*np.pi*df1['day_of_year']/365 )
df1['dayofyear_sin'] = np.sin(2*np.pi*df1['day_of_year']/365)

In [15]:
df.drop('day_of_year',axis=1,inplace=True)
df1.drop('day_of_year',axis=1,inplace=True)

In [16]:
df.head()

,streamflow_today_cumecs,streamflow_anomaly_zscore,flow_rate_of_change,flow_velocity_km_per_day,antecedent_rain_3d_sum,antecedent_rain_7d_sum,antecedent_rain_15d_sum,antecedent_rain_30d_sum,antecedent_rain_60d,antecedent_rain_ewm,...,rain_soilmoisture_interaction,rain_urban_interaction,rain_slope_interaction,rain_basinsize_interaction,uparea_rain_interaction,streamflow_tomorrow_cumecs,month_cos,month_sin,dayofyear_cos,dayofyear_sin
0,51.84180,-0.554512,-0.406627,-1.649524,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,51.435061,0.5,0.866025,0.998667,0.05162
1,570.75726,-0.594236,-5.728960,0.206959,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,565.028190,0.5,0.866025,0.998667,0.05162
2,45.45640,-1.113376,-0.192057,-1.649524,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,45.264231,0.5,0.866025,0.998667,0.05162
3,405.39710,-0.729036,-2.480840,0.769118,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,402.916149,0.5,0.866025,0.998667,0.05162
4,2289.59030,-1.284924,-16.203800,-0.256761,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.518025,-0.514179,-0.514108,-0.519493,-0.472262,2273.386393,0.5,0.866025,0.998667,0.05162

In [ ]:
import matplotlib.pyplot as plt

In [18]:
df.drop('flow_rate_of_change',axis=1, inplace= True)
df1.drop('flow_rate_of_change',axis=1,inplace=True)

In [19]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [20]:
X=df.drop('streamflow_tomorrow_cumecs',axis=1)
y=df['streamflow_tomorrow_cumecs']

In [21]:
split=int(df.shape[0]*0.8)

In [22]:
train=df.iloc[:split]
test=df.iloc[split:]

In [23]:
X_train=train.drop('streamflow_tomorrow_cumecs',axis=1)
y_train=train['streamflow_tomorrow_cumecs']

X_test=test.drop('streamflow_tomorrow_cumecs',axis=1)
y_test=test['streamflow_tomorrow_cumecs']

# Base error

In [24]:
base=X_test['streamflow_today_cumecs']
mean_absolute_error(y_test,base),mean_squared_error(y_test,base)**.5,  r2_score(y_test, base)

(43.755939854379925, 140.80993250221957, 0.9956920809424377)

In [25]:
from sklearn.ensemble import RandomForestRegressor 
from xgboost import XGBRegressor 
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import LinearRegression, Ridge

In [26]:
models  = {
    'xgb' : XGBRegressor(
        n_estimators = 200,
        subsample = 0.75,
        max_depth = 8,
        n_jobs= -1,
        device= 'cuda'
        ),
    'Linear_Regression' : LinearRegression(n_jobs=-1),
    'Ridge':Ridge(),
    'RandomForestRegressor':RandomForestRegressor(
        n_estimators = 300,
        max_depth=11,
        max_samples=.3,
        n_jobs=-1,
    ),
    'Catboost':CatBoostRegressor(
        iterations=400,
        depth=15,
        learning_rate=0.1,
        task_type="GPU",    
    )
}

In [27]:
def training(Model, X_train,y_train,X_test,y_test):
    result = []
    saved_model = {}
    import time 
    
    for name,model in Model.items():
        start = time.perf_counter()
        model.fit(X_train,y_train)
        y_pred = model.predict(X_test)
        
        mae = mean_absolute_error(y_test,y_pred)
        mse = mean_squared_error(y_test,y_pred)
        r2 = r2_score(y_test,y_pred)
        end = time.perf_counter()
        result.append({
            'model':name,
            'MAE':mae,
            "RMSE":mse**0.5,
            'R2_score/NSE':r2,
            'Time_taken(s)' : end- start
        })
        saved_model[name]=model
    return pd.DataFrame(result), saved_model

In [28]:
result,saved_model = training(models ,X_train,y_train,X_test,y_test)

/home/vaibhav/miniconda3/envs/tfenv/lib/python3.10/site-packages/xgboost/core.py:751: UserWarning: [19:22:23] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

0:	learn: 1953.0559100	total: 156ms	remaining: 1m 2s
1:	learn: 1764.2528272	total: 291ms	remaining: 57.8s
2:	learn: 1593.4538120	total: 428ms	remaining: 56.6s
3:	learn: 1440.6840198	total: 584ms	remaining: 57.8s
4:	learn: 1302.4040830	total: 734ms	remaining: 58s
5:	learn: 1177.8390650	total: 882ms	remaining: 57.9s
6:	learn: 1065.6948603	total: 1.04s	remaining: 58.5s
7:	learn: 964.9633677	total: 1.19s	remaining: 58.4s
8:	learn: 874.3312644	total: 1.34s	remaining: 58.4s
9:	learn: 792.1739271	total: 1.5s	remaining: 58.5s
10:	learn: 718.7628434	total: 1.66s	remaining: 58.6s
11:	learn: 652.7909432	total: 1.81s	remaining: 58.7s
12:	learn: 593.8670972	total: 1.97s	remaining: 58.6s
13:	learn: 540.7476280	total: 2.12s	remaining: 58.5s
14:	learn: 492.9457759	total: 2.28s	remaining: 58.5s
15:	learn: 450.4084105	total: 2.44s	remaining: 58.5s
16:	learn: 412.4299476	total: 2.6s	remaining: 58.5s
17:	learn: 378.1263532	total: 2.75s	remaining: 58.4s
18:	learn: 348.0786019	total: 2.9s	remaining: 58.2s
19:	learn: 320.9769336	total: 3.06s	remaining: 58.1s
20:	learn: 296.9160440	total: 3.21s	remaining: 58s
21:	learn: 275.5391917	total: 3.37s	remaining: 57.9s
22:	learn: 256.8025909	total: 3.52s	remaining: 57.7s
23:	learn: 240.2581261	total: 3.67s	remaining: 57.6s
24:	learn: 225.7206512	total: 3.83s	remaining: 57.5s
25:	learn: 212.8467200	total: 3.99s	remaining: 57.4s
26:	learn: 201.7665007	total: 4.14s	remaining: 57.2s
27:	learn: 191.8746668	total: 4.3s	remaining: 57.1s
28:	learn: 183.0077436	total: 4.46s	remaining: 57s
29:	learn: 175.2469933	total: 4.62s	remaining: 57s
30:	learn: 168.7971541	total: 4.77s	remaining: 56.8s
31:	learn: 162.7936969	total: 4.93s	remaining: 56.7s
32:	learn: 157.6293174	total: 5.09s	remaining: 56.6s
33:	learn: 153.1457178	total: 5.25s	remaining: 56.5s
34:	learn: 149.1654220	total: 5.4s	remaining: 56.3s
35:	learn: 145.4151979	total: 5.56s	remaining: 56.2s
36:	learn: 142.2054375	total: 5.72s	remaining: 56.1s
37:	learn: 139.2525101	total: 5.88s	remaining: 56.1s
38:	learn: 136.6126218	total: 6.05s	remaining: 56s
39:	learn: 134.5933924	total: 6.2s	remaining: 55.8s
40:	learn: 132.4774382	total: 6.36s	remaining: 55.7s
41:	learn: 130.3580804	total: 6.53s	remaining: 55.7s
42:	learn: 128.5709354	total: 6.68s	remaining: 55.5s
43:	learn: 126.9302159	total: 6.84s	remaining: 55.3s
44:	learn: 125.5302552	total: 7.01s	remaining: 55.3s
45:	learn: 124.2210648	total: 7.18s	remaining: 55.2s
46:	learn: 122.7257615	total: 7.34s	remaining: 55.1s
47:	learn: 121.5456596	total: 7.5s	remaining: 55s
48:	learn: 120.3626653	total: 7.66s	remaining: 54.9s
49:	learn: 119.3751421	total: 7.83s	remaining: 54.9s
50:	learn: 118.3662676	total: 8s	remaining: 54.7s
51:	learn: 117.3173341	total: 8.15s	remaining: 54.6s
52:	learn: 116.4495038	total: 8.32s	remaining: 54.5s
53:	learn: 115.5181410	total: 8.47s	remaining: 54.3s
54:	learn: 114.5813326	total: 8.63s	remaining: 54.1s
55:	learn: 113.7900572	total: 8.79s	remaining: 54s
56:	learn: 112.8559187	total: 8.95s	remaining: 53.9s
57:	learn: 112.3160512	total: 9.11s	remaining: 53.7s
58:	learn: 111.6789711	total: 9.28s	remaining: 53.6s
59:	learn: 110.9898205	total: 9.43s	remaining: 53.5s
60:	learn: 110.4726205	total: 9.6s	remaining: 53.3s
61:	learn: 109.9212746	total: 9.75s	remaining: 53.2s
62:	learn: 109.2901143	total: 9.91s	remaining: 53s
63:	learn: 108.7204645	total: 10.1s	remaining: 52.9s
64:	learn: 108.0134534	total: 10.2s	remaining: 52.8s
65:	learn: 107.4502264	total: 10.4s	remaining: 52.6s
66:	learn: 106.8137075	total: 10.6s	remaining: 52.4s
67:	learn: 106.0921088	total: 10.7s	remaining: 52.2s
68:	learn: 105.2946604	total: 10.9s	remaining: 52.1s
69:	learn: 104.6007907	total: 11s	remaining: 51.9s
70:	learn: 104.0040144	total: 11.1s	remaining: 51.6s
71:	learn: 103.5888277	total: 11.3s	remaining: 51.5s
72:	learn: 102.9716744	total: 11.4s	remaining: 51.2s
73:	learn: 102.4866482	total: 11.6s	remaining: 51s
74:	learn: 102.0704741	total: 11.7s	remaining: 50.8s
75:	learn: 101.4335959	total: 11.9s	remaining: 50.5s
76:	learn: 100.8575707	total: 12s	remaining: 50.3s
77:	learn: 100.4692549	total: 12.1s	remaining: 50.1s
78:	learn: 100.0934496	total: 12.3s	remaining: 49.9s
79:	learn: 99.3143472	total: 12.4s	remaining: 49.7s
80:	learn: 98.9508000	total: 12.6s	remaining: 49.6s
81:	learn: 98.2598050	total: 12.7s	remaining: 49.3s
82:	learn: 97.7777652	total: 12.9s	remaining: 49.1s
83:	learn: 97.2200391	total: 13s	remaining: 48.8s
84:	learn: 96.7046051	total: 13.1s	remaining: 48.5s
85:	learn: 96.1058748	total: 13.2s	remaining: 48.3s
86:	learn: 95.7284276	total: 13.3s	remaining: 48s
87:	learn: 95.4389168	total: 13.5s	remaining: 47.8s
88:	learn: 95.0216713	total: 13.6s	remaining: 47.5s
89:	learn: 94.4560049	total: 13.7s	remaining: 47.3s
90:	learn: 93.9614880	total: 13.8s	remaining: 47s
91:	learn: 93.5648621	total: 14s	remaining: 46.8s
92:	learn: 93.1013590	total: 14.1s	remaining: 46.5s
93:	learn: 92.5915647	total: 14.2s	remaining: 46.3s
94:	learn: 92.3141288	total: 14.3s	remaining: 46.1s
95:	learn: 91.8810907	total: 14.5s	remaining: 45.8s
96:	learn: 91.4383798	total: 14.6s	remaining: 45.6s
97:	learn: 90.9514010	total: 14.7s	remaining: 45.4s
98:	learn: 90.4886481	total: 14.8s	remaining: 45.1s
99:	learn: 90.2715839	total: 15s	remaining: 44.9s
100:	learn: 89.8700270	total: 15.1s	remaining: 44.7s
101:	learn: 89.3534334	total: 15.2s	remaining: 44.5s
102:	learn: 88.8708976	total: 15.3s	remaining: 44.2s
103:	learn: 88.6240944	total: 15.5s	remaining: 44s
104:	learn: 88.1727125	total: 15.6s	remaining: 43.8s
105:	learn: 87.7393891	total: 15.7s	remaining: 43.6s
106:	learn: 87.3291136	total: 15.9s	remaining: 43.4s
107:	learn: 86.8032316	total: 16s	remaining: 43.3s
108:	learn: 86.4860156	total: 16.1s	remaining: 43.1s
109:	learn: 86.0730425	total: 16.3s	remaining: 42.9s
110:	learn: 85.7763302	total: 16.4s	remaining: 42.7s
111:	learn: 85.4165692	total: 16.5s	remaining: 42.5s
112:	learn: 85.0624242	total: 16.7s	remaining: 42.4s
113:	learn: 84.7271494	total: 16.8s	remaining: 42.2s
114:	learn: 84.3533123	total: 17s	remaining: 42s
115:	learn: 84.0045407	total: 17.1s	remaining: 41.8s
116:	learn: 83.6067866	total: 17.2s	remaining: 41.7s
117:	learn: 83.2157016	total: 17.4s	remaining: 41.5s
118:	learn: 82.8868799	total: 17.5s	remaining: 41.3s
119:	learn: 82.5847338	total: 17.7s	remaining: 41.2s
120:	learn: 82.2012479	total: 17.8s	remaining: 41s
121:	learn: 81.8553341	total: 17.9s	remaining: 40.8s
122:	learn: 81.5412157	total: 18.1s	remaining: 40.7s
123:	learn: 81.2023522	total: 18.2s	remaining: 40.5s
124:	learn: 80.9601268	total: 18.3s	remaining: 40.3s
125:	learn: 80.6260118	total: 18.5s	remaining: 40.1s
126:	learn: 80.3119483	total: 18.6s	remaining: 39.9s
127:	learn: 80.0741329	total: 18.7s	remaining: 39.8s
128:	learn: 79.7400702	total: 18.9s	remaining: 39.7s
129:	learn: 79.4434748	total: 19s	remaining: 39.5s
130:	learn: 79.1401441	total: 19.1s	remaining: 39.3s
131:	learn: 78.7759625	total: 19.3s	remaining: 39.2s
132:	learn: 78.4658197	total: 19.4s	remaining: 39s
133:	learn: 78.2106037	total: 19.6s	remaining: 38.8s
134:	learn: 77.9118984	total: 19.7s	remaining: 38.7s
135:	learn: 77.6251411	total: 19.8s	remaining: 38.5s
136:	learn: 77.3179511	total: 20s	remaining: 38.3s
137:	learn: 77.0322529	total: 20.1s	remaining: 38.2s
138:	learn: 76.7821731	total: 20.2s	remaining: 38s
139:	learn: 76.4972626	total: 20.4s	remaining: 37.8s
140:	learn: 76.2155298	total: 20.5s	remaining: 37.7s
141:	learn: 75.9662675	total: 20.6s	remaining: 37.5s
142:	learn: 75.7494741	total: 20.8s	remaining: 37.3s
143:	learn: 75.4679414	total: 20.9s	remaining: 37.2s
144:	learn: 75.1981562	total: 21.1s	remaining: 37s
145:	learn: 74.8923455	total: 21.2s	remaining: 36.9s
146:	learn: 74.6665170	total: 21.3s	remaining: 36.7s
147:	learn: 74.4691939	total: 21.5s	remaining: 36.6s
148:	learn: 74.1817220	total: 21.6s	remaining: 36.4s
149:	learn: 73.9363768	total: 21.8s	remaining: 36.3s
150:	learn: 73.7520297	total: 21.9s	remaining: 36.1s
151:	learn: 73.5915721	total: 22s	remaining: 36s
152:	learn: 73.3971924	total: 22.2s	remaining: 35.8s
153:	learn: 73.1758360	total: 22.3s	remaining: 35.6s
154:	learn: 73.0381299	total: 22.4s	remaining: 35.5s
155:	learn: 72.7692224	total: 22.6s	remaining: 35.3s
156:	learn: 72.5275079	total: 22.7s	remaining: 35.2s
157:	learn: 72.3088353	total: 22.9s	remaining: 35s
158:	learn: 72.1266718	total: 23s	remaining: 34.8s
159:	learn: 71.8603256	total: 23.1s	remaining: 34.7s
160:	learn: 71.7080838	total: 23.3s	remaining: 34.5s
161:	learn: 71.5172867	total: 23.4s	remaining: 34.4s
162:	learn: 71.2663736	total: 23.5s	remaining: 34.2s
163:	learn: 71.0484162	total: 23.7s	remaining: 34.1s
164:	learn: 70.8446351	total: 23.8s	remaining: 33.9s
165:	learn: 70.6178438	total: 23.9s	remaining: 33.7s
166:	learn: 70.4072872	total: 24.1s	remaining: 33.6s
167:	learn: 70.1753901	total: 24.2s	remaining: 33.4s
168:	learn: 69.9694612	total: 24.3s	remaining: 33.3s
169:	learn: 69.7289580	total: 24.5s	remaining: 33.1s
170:	learn: 69.5161388	total: 24.6s	remaining: 33s
171:	learn: 69.3058843	total: 24.8s	remaining: 32.8s
172:	learn: 69.1462583	total: 24.9s	remaining: 32.7s
173:	learn: 68.9284405	total: 25s	remaining: 32.5s
174:	learn: 68.7588485	total: 25.2s	remaining: 32.4s
175:	learn: 68.6026342	total: 25.3s	remaining: 32.2s
176:	learn: 68.3612986	total: 25.4s	remaining: 32s
177:	learn: 68.0900140	total: 25.6s	remaining: 31.9s
178:	learn: 67.9171593	total: 25.7s	remaining: 31.8s
179:	learn: 67.7688933	total: 25.8s	remaining: 31.6s
180:	learn: 67.6099462	total: 26s	remaining: 31.4s
181:	learn: 67.4590567	total: 26.1s	remaining: 31.3s
182:	learn: 67.2783877	total: 26.2s	remaining: 31.1s
183:	learn: 67.1017694	total: 26.4s	remaining: 30.9s
184:	learn: 66.8838771	total: 26.5s	remaining: 30.8s
185:	learn: 66.6882849	total: 26.6s	remaining: 30.6s
186:	learn: 66.5030554	total: 26.7s	remaining: 30.5s
187:	learn: 66.3156495	total: 26.9s	remaining: 30.3s
188:	learn: 66.1447664	total: 27s	remaining: 30.1s
189:	learn: 65.9407649	total: 27.1s	remaining: 30s
190:	learn: 65.7570450	total: 27.3s	remaining: 29.8s
191:	learn: 65.5418263	total: 27.4s	remaining: 29.7s
192:	learn: 65.3476910	total: 27.5s	remaining: 29.5s
193:	learn: 65.2470229	total: 27.6s	remaining: 29.3s
194:	learn: 65.0347401	total: 27.8s	remaining: 29.2s
195:	learn: 64.8691707	total: 27.9s	remaining: 29s
196:	learn: 64.7345245	total: 28s	remaining: 28.9s
197:	learn: 64.5553749	total: 28.2s	remaining: 28.7s
198:	learn: 64.4390679	total: 28.3s	remaining: 28.6s
199:	learn: 64.2470829	total: 28.4s	remaining: 28.4s
200:	learn: 64.0656709	total: 28.5s	remaining: 28.3s
201:	learn: 63.9239938	total: 28.7s	remaining: 28.1s
202:	learn: 63.7757750	total: 28.8s	remaining: 27.9s
203:	learn: 63.5994748	total: 28.9s	remaining: 27.8s
204:	learn: 63.4058251	total: 29s	remaining: 27.6s
205:	learn: 63.2346721	total: 29.2s	remaining: 27.5s
206:	learn: 63.0664708	total: 29.3s	remaining: 27.3s
207:	learn: 62.9425150	total: 29.4s	remaining: 27.2s
208:	learn: 62.8423076	total: 29.6s	remaining: 27s
209:	learn: 62.6489299	total: 29.7s	remaining: 26.9s
210:	learn: 62.5246798	total: 29.8s	remaining: 26.7s
211:	learn: 62.3854046	total: 29.9s	remaining: 26.5s
212:	learn: 62.2015964	total: 30.1s	remaining: 26.4s
213:	learn: 62.0253930	total: 30.2s	remaining: 26.2s
214:	learn: 61.8725275	total: 30.3s	remaining: 26.1s
215:	learn: 61.7199187	total: 30.4s	remaining: 25.9s
216:	learn: 61.6072772	total: 30.6s	remaining: 25.8s
217:	learn: 61.4259246	total: 30.7s	remaining: 25.6s
218:	learn: 61.2561824	total: 30.9s	remaining: 25.5s
219:	learn: 61.1176252	total: 31s	remaining: 25.4s
220:	learn: 60.9636145	total: 31.1s	remaining: 25.2s
221:	learn: 60.8180348	total: 31.2s	remaining: 25.1s
222:	learn: 60.6768279	total: 31.4s	remaining: 24.9s
223:	learn: 60.5802403	total: 31.5s	remaining: 24.8s
224:	learn: 60.4271711	total: 31.6s	remaining: 24.6s
225:	learn: 60.2508642	total: 31.8s	remaining: 24.4s
226:	learn: 60.1346556	total: 31.9s	remaining: 24.3s
227:	learn: 60.0107974	total: 32s	remaining: 24.1s
228:	learn: 59.8609732	total: 32.1s	remaining: 24s
229:	learn: 59.7204315	total: 32.3s	remaining: 23.8s
230:	learn: 59.5486433	total: 32.4s	remaining: 23.7s
231:	learn: 59.4250446	total: 32.5s	remaining: 23.6s
232:	learn: 59.2813133	total: 32.7s	remaining: 23.4s
233:	learn: 59.0853831	total: 32.8s	remaining: 23.3s
234:	learn: 58.9257888	total: 32.9s	remaining: 23.1s
235:	learn: 58.8028705	total: 33s	remaining: 23s
236:	learn: 58.7053410	total: 33.2s	remaining: 22.8s
237:	learn: 58.5981494	total: 33.3s	remaining: 22.7s
238:	learn: 58.4661747	total: 33.4s	remaining: 22.5s
239:	learn: 58.3297342	total: 33.6s	remaining: 22.4s
240:	learn: 58.2601359	total: 33.7s	remaining: 22.2s
241:	learn: 58.1291045	total: 33.8s	remaining: 22.1s
242:	learn: 57.9994403	total: 33.9s	remaining: 21.9s
243:	learn: 57.8892453	total: 34.1s	remaining: 21.8s
244:	learn: 57.7595920	total: 34.2s	remaining: 21.6s
245:	learn: 57.6645846	total: 34.3s	remaining: 21.5s
246:	learn: 57.5261435	total: 34.4s	remaining: 21.3s
247:	learn: 57.4088161	total: 34.6s	remaining: 21.2s
248:	learn: 57.2862169	total: 34.7s	remaining: 21s
249:	learn: 57.1572709	total: 34.8s	remaining: 20.9s
250:	learn: 57.0474411	total: 34.9s	remaining: 20.7s
251:	learn: 56.9102674	total: 35.1s	remaining: 20.6s
252:	learn: 56.7881852	total: 35.2s	remaining: 20.4s
253:	learn: 56.6874092	total: 35.3s	remaining: 20.3s
254:	learn: 56.5492786	total: 35.4s	remaining: 20.2s
255:	learn: 56.4207926	total: 35.6s	remaining: 20s
256:	learn: 56.3227205	total: 35.7s	remaining: 19.9s
257:	learn: 56.2326672	total: 35.9s	remaining: 19.7s
258:	learn: 56.1785934	total: 36s	remaining: 19.6s
259:	learn: 56.0667888	total: 36.1s	remaining: 19.4s
260:	learn: 55.9677938	total: 36.2s	remaining: 19.3s
261:	learn: 55.8982383	total: 36.4s	remaining: 19.2s
262:	learn: 55.7837344	total: 36.5s	remaining: 19s
263:	learn: 55.6748925	total: 36.6s	remaining: 18.9s
264:	learn: 55.5674614	total: 36.8s	remaining: 18.7s
265:	learn: 55.5168223	total: 36.9s	remaining: 18.6s
266:	learn: 55.4165372	total: 37s	remaining: 18.4s
267:	learn: 55.3392475	total: 37.1s	remaining: 18.3s
268:	learn: 55.2439731	total: 37.3s	remaining: 18.1s
269:	learn: 55.1051695	total: 37.4s	remaining: 18s
270:	learn: 55.0083561	total: 37.5s	remaining: 17.9s
271:	learn: 54.8788593	total: 37.6s	remaining: 17.7s
272:	learn: 54.7470214	total: 37.8s	remaining: 17.6s
273:	learn: 54.6251469	total: 37.9s	remaining: 17.4s
274:	learn: 54.5410516	total: 38s	remaining: 17.3s
275:	learn: 54.4416462	total: 38.2s	remaining: 17.1s
276:	learn: 54.3965742	total: 38.3s	remaining: 17s
277:	learn: 54.3038448	total: 38.4s	remaining: 16.9s
278:	learn: 54.2531182	total: 38.5s	remaining: 16.7s
279:	learn: 54.1476933	total: 38.7s	remaining: 16.6s
280:	learn: 54.0279131	total: 38.8s	remaining: 16.4s
281:	learn: 53.9078714	total: 38.9s	remaining: 16.3s
282:	learn: 53.8142953	total: 39s	remaining: 16.1s
283:	learn: 53.7356182	total: 39.2s	remaining: 16s
284:	learn: 53.6421361	total: 39.3s	remaining: 15.9s
285:	learn: 53.5235545	total: 39.4s	remaining: 15.7s
286:	learn: 53.4261628	total: 39.5s	remaining: 15.6s
287:	learn: 53.3628132	total: 39.7s	remaining: 15.4s
288:	learn: 53.2576100	total: 39.8s	remaining: 15.3s
289:	learn: 53.1571110	total: 39.9s	remaining: 15.1s
290:	learn: 53.0502236	total: 40s	remaining: 15s
291:	learn: 52.9498129	total: 40.2s	remaining: 14.9s
292:	learn: 52.8454433	total: 40.3s	remaining: 14.7s
293:	learn: 52.7844409	total: 40.4s	remaining: 14.6s
294:	learn: 52.7095255	total: 40.5s	remaining: 14.4s
295:	learn: 52.6285891	total: 40.7s	remaining: 14.3s
296:	learn: 52.5194294	total: 40.8s	remaining: 14.2s
297:	learn: 52.4406561	total: 40.9s	remaining: 14s
298:	learn: 52.3774002	total: 41.1s	remaining: 13.9s
299:	learn: 52.2766495	total: 41.2s	remaining: 13.7s
300:	learn: 52.1996248	total: 41.3s	remaining: 13.6s
301:	learn: 52.0868899	total: 41.4s	remaining: 13.4s
302:	learn: 52.0207443	total: 41.6s	remaining: 13.3s
303:	learn: 51.9591354	total: 41.7s	remaining: 13.2s
304:	learn: 51.8773570	total: 41.8s	remaining: 13s
305:	learn: 51.7839765	total: 41.9s	remaining: 12.9s
306:	learn: 51.6936922	total: 42.1s	remaining: 12.7s
307:	learn: 51.5886945	total: 42.2s	remaining: 12.6s
308:	learn: 51.5212111	total: 42.3s	remaining: 12.5s
309:	learn: 51.4036375	total: 42.4s	remaining: 12.3s
310:	learn: 51.3128733	total: 42.6s	remaining: 12.2s
311:	learn: 51.2218534	total: 42.7s	remaining: 12s
312:	learn: 51.1413176	total: 42.8s	remaining: 11.9s
313:	learn: 51.0660780	total: 43s	remaining: 11.8s
314:	learn: 50.9995260	total: 43.1s	remaining: 11.6s
315:	learn: 50.9480380	total: 43.2s	remaining: 11.5s
316:	learn: 50.8608338	total: 43.3s	remaining: 11.3s
317:	learn: 50.7677850	total: 43.4s	remaining: 11.2s
318:	learn: 50.6759556	total: 43.6s	remaining: 11.1s
319:	learn: 50.5429236	total: 43.7s	remaining: 10.9s
320:	learn: 50.4474382	total: 43.8s	remaining: 10.8s
321:	learn: 50.3670158	total: 43.9s	remaining: 10.6s
322:	learn: 50.2556432	total: 44.1s	remaining: 10.5s
323:	learn: 50.1523624	total: 44.2s	remaining: 10.4s
324:	learn: 50.0625466	total: 44.3s	remaining: 10.2s
325:	learn: 49.9726890	total: 44.4s	remaining: 10.1s
326:	learn: 49.8874074	total: 44.6s	remaining: 9.95s
327:	learn: 49.7987958	total: 44.7s	remaining: 9.81s
328:	learn: 49.6951341	total: 44.8s	remaining: 9.68s
329:	learn: 49.6289606	total: 45s	remaining: 9.54s
330:	learn: 49.5410198	total: 45.1s	remaining: 9.4s
331:	learn: 49.4540074	total: 45.2s	remaining: 9.26s
332:	learn: 49.3915000	total: 45.3s	remaining: 9.12s
333:	learn: 49.2765917	total: 45.5s	remaining: 8.98s
334:	learn: 49.2000461	total: 45.6s	remaining: 8.85s
335:	learn: 49.1002688	total: 45.7s	remaining: 8.71s
336:	learn: 49.0274210	total: 45.9s	remaining: 8.57s
337:	learn: 48.9348233	total: 46s	remaining: 8.43s
338:	learn: 48.9065525	total: 46.1s	remaining: 8.29s
339:	learn: 48.8369100	total: 46.2s	remaining: 8.16s
340:	learn: 48.7571598	total: 46.4s	remaining: 8.02s
341:	learn: 48.7010855	total: 46.5s	remaining: 7.88s
342:	learn: 48.6228610	total: 46.6s	remaining: 7.75s
343:	learn: 48.5002991	total: 46.7s	remaining: 7.61s
344:	learn: 48.4645667	total: 46.9s	remaining: 7.47s
345:	learn: 48.4055026	total: 47s	remaining: 7.33s
346:	learn: 48.2982115	total: 47.1s	remaining: 7.2s
347:	learn: 48.2366268	total: 47.3s	remaining: 7.06s
348:	learn: 48.1693411	total: 47.4s	remaining: 6.92s
349:	learn: 48.1031128	total: 47.5s	remaining: 6.79s
350:	learn: 48.0102256	total: 47.6s	remaining: 6.65s
351:	learn: 47.9328911	total: 47.8s	remaining: 6.51s
352:	learn: 47.8899007	total: 47.9s	remaining: 6.38s
353:	learn: 47.7973700	total: 48s	remaining: 6.24s
354:	learn: 47.7165450	total: 48.2s	remaining: 6.11s
355:	learn: 47.6252742	total: 48.3s	remaining: 5.97s
356:	learn: 47.5571864	total: 48.4s	remaining: 5.83s
357:	learn: 47.4946905	total: 48.5s	remaining: 5.69s
358:	learn: 47.4108137	total: 48.7s	remaining: 5.56s
359:	learn: 47.3290130	total: 48.8s	remaining: 5.42s
360:	learn: 47.2459300	total: 48.9s	remaining: 5.28s
361:	learn: 47.1771048	total: 49s	remaining: 5.15s
362:	learn: 47.1155815	total: 49.2s	remaining: 5.01s
363:	learn: 47.0187821	total: 49.3s	remaining: 4.88s
364:	learn: 46.9674112	total: 49.4s	remaining: 4.74s
365:	learn: 46.8903609	total: 49.5s	remaining: 4.6s
366:	learn: 46.8069859	total: 49.7s	remaining: 4.47s
367:	learn: 46.7372640	total: 49.8s	remaining: 4.33s
368:	learn: 46.6671952	total: 49.9s	remaining: 4.2s
369:	learn: 46.5682825	total: 50.1s	remaining: 4.06s
370:	learn: 46.5055844	total: 50.2s	remaining: 3.92s
371:	learn: 46.4478531	total: 50.3s	remaining: 3.79s
372:	learn: 46.4000858	total: 50.5s	remaining: 3.65s
373:	learn: 46.3417047	total: 50.6s	remaining: 3.52s
374:	learn: 46.1978202	total: 50.7s	remaining: 3.38s
375:	learn: 46.1187042	total: 50.9s	remaining: 3.25s
376:	learn: 46.0629685	total: 51s	remaining: 3.11s
377:	learn: 45.9632781	total: 51.1s	remaining: 2.98s
378:	learn: 45.8908777	total: 51.2s	remaining: 2.84s
379:	learn: 45.8189088	total: 51.4s	remaining: 2.7s

In [30]:
result

                   model        MAE        RMSE  R2_score/NSE  Time_taken(s)
0                    xgb  31.429215  105.047581      0.997602       4.679193
1      Linear_Regression  48.691251  136.536012      0.995950       2.139689
2                  Ridge  48.688476  136.533953      0.995950       0.421376
3  RandomForestRegressor  38.379490  125.883326      0.996557     363.839292
4               Catboost  35.000879   96.903901      0.997960      55.436767

In [31]:
result.sort_values('MAE')

                   model        MAE        RMSE  R2_score/NSE  Time_taken(s)
0                    xgb  31.429215  105.047581      0.997602       4.679193
4               Catboost  35.000879   96.903901      0.997960      55.436767
3  RandomForestRegressor  38.379490  125.883326      0.996557     363.839292
2                  Ridge  48.688476  136.533953      0.995950       0.421376
1      Linear_Regression  48.691251  136.536012      0.995950       2.139689